/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 human_body.glb -T 
Files: human_body.glb [978.96KB] > D:\workspace\DEMO\digital-body\public\model\human_body-transformed.glb [85.35KB] (91%)
Author: vistaalienprime (https://sketchfab.com/vistaalienprime5665288)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-body-f022e4a3641943328b2fbfdf0f7c3e1e
Title: HUMAN_BODY
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/human_body-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={2.113} />
    </group>
  )
}

useGLTF.preload('/human_body-transformed.glb')
