/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 male_body.glb -T 
Files: male_body.glb [1.58MB] > D:\workspace\DEMO\digital-body\public\model\male_body-transformed.glb [68.5KB] (96%)
Author: Alexander Antipov (https://sketchfab.com/Dessen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/male-body-15a422001834483c9750ce6117d59cc1
Title: Male Body
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/male_body-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Low_Poly_Male_bodyGroup2_lambert1_0.geometry} material={materials.lambert1} />
    </group>
  )
}

useGLTF.preload('/male_body-transformed.glb')
